@startuml Docflows 23 incoming StateMachine

state "Подтверждается получение" as ConfirmedReceiving
state "Требуется подтверждение получения" as RequiredDeliveryConfirmation
state "Завершён" as Completed

[*] --> ConfirmedReceiving : Первичный документ получен
ConfirmedReceiving --> RequiredDeliveryConfirmation : ИоП НЕ подписан/сформирован \n(внутреннее событие)
ConfirmedReceiving --> Completed : Иоп отправлен \n(ответная подпись НЕ запрошена)
RequiredDeliveryConfirmation --> Completed : ИоП отправлен \n(ответная подпись НЕ запрошена)
Completed --> [*]

note left of Completed : Аннулирование расписано на отдельной диаграмме \n (доступно только если ответная подпись запрошена)
note left of ConfirmedReceiving : ИоП НЕ отправлен на оператор - выполняется повторная отправка ИоП,\n статус документа при этом не меняется 

@enduml