@startuml Docflows 28 schf incoming StateMachine

state "Ожидается ПДО" as waitingDPO
state "Ожидается первичный документ" as waitingPrimaryDocument
state "Требуется подтверждение получения" as RequiredDeliveryConfirmation
state "подтверждается получение" as Accept
state "Отклонен" as Rejected
state "Отклоняется" as Rejection
state "Завершён" as Completed

[*] --> waitingPrimaryDocument : получено подтверждение оператора
[*] --> waitingDPO : получен Первичный документ 
waitingPrimaryDocument --> RequiredDeliveryConfirmation : получен Первичный документ
waitingDPO --> RequiredDeliveryConfirmation : получено подтверждение оператора
RequiredDeliveryConfirmation --> Accept : Принять документ
Accept --> RequiredDeliveryConfirmation : ошибка формирования, подписани, отправки ИоП \n(внутреннее событие)
Accept --> Completed : Иоп отправлен
Completed --> [*]

RequiredDeliveryConfirmation --> Rejection : "Отклонить документ" \n(внутреннее событие)
Rejection --> RequiredDeliveryConfirmation : ошибка формирования, подписани, отправки УоУ \n(внутреннее событие)
Rejection --> Rejected : НЕсогласие с документом (УОУ) отправлено на оператор 
Rejected --> [*]

note left of waitingDPO : служебное состояние скрыто для пользователя
note left of waitingPrimaryDocument : служебное состояние скрыто для пользователя
note left of Completed : Аннулирование расписано \n на отдельной диаграмме
note bottom of Rejection : УОУ не отправлен - выполняется повторная отправка УОУ на оператор,\n статус документа при этом не меняется

@enduml