@startuml
actor "Продавец" as user
participant "Оператор ЭДО Продавца" as prod
participant "Оператор ЭДО Покупателя" as pok
actor "Покупатель" as user1
activate user
activate prod 
        user -> prod: 1.ДокументОПередачеРезультатовРаботИсполнитель
  alt 
        prod  -[#red]> user: 2а. Сообщение об ошибке
        note left: Проверка не пройдена
  end 
   prod  -[#green]> user: 2б. ПодтверждениеДатыПоступления на\nДокументОПередачеРезультатовРаботИсполнитель
   note left: Проверка пройдена
  deactivate user
  prod -> pok: 3.ДокументОПередачеРезультатовРаботИсполнитель
  deactivate prod
  activate pok 
  pok -> user1: 4.ДокументОПередачеРезультатовРаботИсполнитель
  activate user1 
  pok -> user1: 5.ПодтверждениеДатыОтправки на\nДокументОПередачеРезультатовРаботИсполнитель
  pok -> prod: 6.ПодтверждениеОператора на\nДокументОПередачеРезультатовРаботИсполнитель 
  activate prod 
  user1 -> pok: 7.ИзвещениеОПолучении на\nДокументОПередачеРезультатовРаботИсполнитель 
  deactivate user1
  pok -> prod: 8.ИзвещениеОПолучении на\nДокументОПередачеРезультатовРаботИсполнитель 
  deactivate pok
  prod -> user: 9.ИзвещениеОПолучении на\nДокументОПередачеРезультатовРаботИсполнитель 
  activate user 
  deactivate user
  deactivate prod
   alt 
     user1  -[#red]> pok: 10.УведомлениеОбУточнении на\nДокументОПередачеРезультатовРаботИсполнитель 
     activate user1
     activate pok
      note left: Получатель отклонил документ
     pok -> prod: 11.УведомлениеОбУточнении на\nДокументОПередачеРезультатовРаботИсполнитель
     activate prod 
     pok -> user1: 12.ПодтверждениеДатыПоступления на\nУведомлениеОбУточнении 
     deactivate user1
     prod -> user: 13.УведомлениеОбУточнении на\nДокументОПередачеРезультатовРаботИсполнитель 
     activate user
     prod -> user: 14.ПодтверждениеДатыОтправки на\nУведомлениеОбУточнении 
     deactivate user
     prod -> pok: 15.ПодтверждениеОператора на\nУведомлениеОбУточнении 
   deactivate prod
   deactivate pok
   end
   alt 
     user1  -[#green]> pok: 10.ДокументОПередачеРезультатовРаботЗаказчик. 
    note left: Получатель принял документ
     activate user1
     activate pok
     pok -> prod: 11.ДокументОПередачеРезультатовРаботЗаказчик
     activate prod 
     pok -> user1: 12.ПодтверждениеДатыПоступления на\nДокументОПередачеРезультатовРаботЗаказчик
     prod -> user: 13.ДокументОПередачеРезультатовРаботЗаказчик 
     activate user
     prod -> user: 14.ПодтверждениеДатыОтправки на\nДокументОПередачеРезультатовРаботЗаказчик 
     prod -> pok: 15.ПодтверждениеОператора на\nДокументОПередачеРезультатовРаботЗаказчик 
     user -> prod: 16.ИзвещениеОПолучении на\nДокументОПередачеРезультатовРаботЗаказчик
     deactivate user
     prod -> pok: 17.ИзвещениеОПолучении на\nДокументОПередачеРезультатовРаботЗаказчик
     deactivate prod
     pok -> user1: 18.ИзвещениеОПолучении на\nДокументОПередачеРезультатовРаботЗаказчик
    deactivate pok
   deactivate user1
   end
@enduml