@startuml styles
skinparam {
'monochrome true
'actorStyle awesome
BackgroundColor White
BoxPadding 10
Roundcorner 10
Maxmessagesize 300
DatabaseBackgroundColor Wheat
DatabaseBorderColor IndianRed
DatabaseBorderThickness 2
DatabaseFontColor Black
DatabaseFontSize 14
QueueBackgroundColor Wheat
QueueBorderColor IndianRed
QueueBorderThickness 2
QueueFontColor Black
QueueFontSize 14
}
skinparam note {
BackgroundColor BlanchedAlmond
BorderColor SandyBrown
}
skinparam title {
BorderRoundCorner 10
BorderThickness 1.5
BorderColor Firebrick
BackgroundColor MistyRose
FontSize 20
}
skinparam sequence {
ArrowThickness 1.5
ParticipantFontSize 14
ParticipantPadding 30
BoxBackgroundColor Azure
MessageAlign center
ArrowColor DarkBlue
ArrowFontColor Black
LifeLineBorderColor DarkGray
LifeLineBackgroundColor SlateGray
GroupBackgroundColor LightGray
GroupBorderColor DimGray
ActorBackgroundColor Moccasin
ActorBorderColor Maroon
ActorFontColor Black
ParticipantBackgroundColor PeachPuff
ParticipantBorderColor Sienna
ParticipantFontColor Black
}
hide footbox
autonumber 45 5 "<font color=red><b>Message 0 "
title Your diagram title here
box Net segment Public
actor Aaaactor as act
end box
box Net segment A
participant "__Cooomponent__" as a
database Daaatabase as db
end box
box Net segment B
queue "Broooker" as b
end box
act -> a: Hi there
Group Custom group name
a -> b: request many parameters
return response with response code
note left: aaa
end
@enduml