@startuml Docflows 25 and 26 outgoing StateMachine
state "Ожидается подтверждение оператора" as WaitingOperatorAproove
state "Ожидается ИоП" as WaitingInvoice
state "Ожидается ответная подпись" as WaitingAnswer
state "Завершён" as Copmleted
state "Отклонён" as Rejected
state "Подписывается" as Signing
state "Готов к отправке" as ReadyToSend

[*] --> ReadyToSend : Первичный документ загружен
ReadyToSend --> Signing : Отправить первичный документ
Signing --> ReadyToSend : Ошибка подписания
Signing --> WaitingOperatorAproove : Первичный документ отправлен
WaitingOperatorAproove --> WaitingInvoice : Получен ПДП
WaitingInvoice --> WaitingAnswer : Получен ИоП
WaitingAnswer --> Copmleted : Получено согласие с первичкой

Copmleted --> [*]
note left of Copmleted : Аннулирование расписано   \nна отдельной диаграмме


WaitingAnswer --> Rejected : Получено УоУ на первичку
Rejected --> [*]

@enduml