@startuml Docflows 24 incoming StateMachine

state "Подтверждается получение" as ConfirmedReceiving
state "Требуется подтверждение получения" as RequiredDeliveryConfirmation
state "Завершён" as Completed
state "Требуется ответная подпись" as ResponseSignatureRequired
state "Подписывается" as Signing
state "Отклоняется" as Rejection
state "Завершён" as Completed
state "Отклонен" as Rejected

[*] --> ConfirmedReceiving : Первичный документ получен
ConfirmedReceiving --> RequiredDeliveryConfirmation : ИоП НЕ подписан/сформирован \n(внутреннее событие)
RequiredDeliveryConfirmation --> ResponseSignatureRequired : ИоП отправлен
ConfirmedReceiving --> ResponseSignatureRequired : ИоП отправлен

ResponseSignatureRequired --> Signing : "Подписать документ" \n(внутреннее событие)
Signing --> ResponseSignatureRequired : Ошибка подписания титула продавца \n(внутреннее событие)
Signing --> Completed : Ответный титул отправлен

ResponseSignatureRequired --> Rejection : "Отклонить документ" \n(внутреннее событие)
Rejection --> ResponseSignatureRequired : Ошибка подписания УОУ \n(внутреннее событие)
Rejection --> Rejected : УоУ отправлен

Rejected --> [*]
Completed --> [*]

note left of Completed : Аннулирование расписано на отдельной диаграмме \n (доступно только если ответная подпись запрошена)
note left of ConfirmedReceiving : ИоП НЕ отправлен на оператор - выполняется повторная отправка ИоП,\n статус документа при этом не меняется 

@enduml